# Generated by Django 3.2.11 on 2022-02-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.TextField(blank=True, verbose_name="цвет"),
        ),
    ]
