# Generated by Django 3.2.11 on 2022-02-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_product_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
    ]
