# Generated by Django 3.2.11 on 2022-02-18 17:54

from django.db import migrations, models

import authapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_auto_20220129_2007"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopuser",
            name="activation_key",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=authapp.models.get_activation_key_expiration_date
            ),
        ),
    ]
